// To parse this JSON data, do
//
//     final intercambio = intercambioFromMap(jsonString);

import 'dart:convert';

class Intercambio {
  Intercambio({
    required this.folio,
    required this.carro,
    required this.usuario,
    required this.fechaGuard,
    required this.anio,
    required this.motor,
    required this.placa,
    required this.marca,
    required this.noVin,
    required this.color,
    required this.modelo,
    required this.km,
    required this.nivelAceite,
    required this.combustible,
    required this.motorOk,
    required this.transmision,
    required this.ejes,
    required this.sucursal,
    required this.firmaOp,
    required this.firmaRep,
    required this.frontalImg,
    required this.placaDel,
    required this.defensa,
    required this.defCom,
    required this.cofreCentr,
    required this.cofreCentrCom,
    required this.parrilla,
    required this.parrillaCom,
    required this.faros,
    required this.farosCom,
    required this.parabrisas,
    required this.parabrisasCom,
    required this.copete,
    required this.copeteCom,
    required this.engomados,
    required this.conchasEspe,
    required this.conchasEspeCom,
    required this.iave,
    required this.colchonImg,
    required this.colch,
    required this.colchCom,
    required this.tableroImg,
    required this.controles,
    required this.controlesCom,
    required this.estereo,
    required this.estereoCom,
    required this.interiorImg,
    required this.llavesEncend,
    required this.llavesEncendCom,
    required this.tapiceria,
    required this.tapiceriaCom,
    required this.limpiezaUnidad,
    required this.limpiezaUnidadCom,
    required this.video,
    required this.carpeta,
    required this.carpetaCom,
    required this.accom,
    required this.ac,
    required this.lateralDer1Img,
    required this.defLateDer,
    required this.defLateDerCom,
    required this.cofLateDer,
    required this.cofLateDerCom,
    required this.espCofreDer,
    required this.espCofreDerCom,
    required this.llantaPos2,
    required this.llantaPos2Com,
    required this.lateralDer2Img,
    required this.faldonesDer,
    required this.faldonesDerCom,
    required this.estribosDer,
    required this.estribosDerCom,
    required this.puertaDer,
    required this.puertaDerCom,
    required this.ventanasDer,
    required this.ventanasDerCom,
    required this.conchEspeDer,
    required this.conchEspeDerCom,
    required this.costadoDerCab,
    required this.costadoDerCabCom,
    required this.aleronesDer,
    required this.aleronesDerCom,
    required this.copeteCostDer,
    required this.copeteCostDerCom,
    required this.lateralIzq1Img,
    required this.defLateIzq,
    required this.defLateIzqCom,
    required this.cofLateIzq,
    required this.cofLateIzqCom,
    required this.espCofreIzq,
    required this.espCofreIzqCom,
    required this.llantaPos1,
    required this.llantaPos1Com,
    required this.lateralIzq2Img,
    required this.faldonesIzq,
    required this.faldonesIzqCom,
    required this.estribosIzq,
    required this.estribosIzqCom,
    required this.puertaIzq,
    required this.puertaIzqCom,
    required this.ventanasIzq,
    required this.ventanasIzqCom,
    required this.conchEspIzq,
    required this.conchEspIzqCom,
    required this.costadoIzqCab,
    required this.costadoIzqCabCom,
    required this.aleronesIzq,
    required this.aleronesIzqCom,
    required this.copeteCostIzq,
    required this.copeteCostIzqCom,
    required this.trampasImg,
    required this.trampaIzq,
    required this.trampaIzqCom,
    required this.trampaDer,
    required this.trampaDerCom,
    required this.acumuladoresImg,
    required this.acum,
    required this.acumCom,
    required this.trampaDerImg,
    required this.trasera1Img,
    required this.placaTrasera,
    required this.portaloderas,
    required this.portaloderasCom,
    required this.loderas,
    required this.loderasCom,
    required this.bolsas,
    required this.bolsasCom,
    required this.quinta,
    required this.quintaCom,
    required this.lucesTras,
    required this.lucesTrasCom,
    required this.espaldaCab,
    required this.eslpadaCabCom,
    required this.mangueServicio,
    required this.mangueServicioCom,
    required this.chirriones,
    required this.chirrionesCom,
    required this.silenciador,
    required this.silenciadorCom,
    required this.mallaEscape,
    required this.mallaEscapeCom,
    required this.llantaPos3,
    required this.llantaPos3Com,
    required this.trasera2Img,
    required this.guardafangos,
    required this.guardafangosCom,
    required this.plataformaTrabajo,
    required this.plataformaTrabajoCom,
    required this.miembrosTransv,
    required this.miembrosTransvCom,
    required this.bastidores,
    required this.bastidoresCom,
    required this.llantaPos4,
    required this.llantaPos4Com,
    required this.llantaPos5,
    required this.llantaPos5Com,
    required this.llantaPos6,
    required this.llantaPos6Com,
    required this.llantaPos7,
    required this.llantaPos7Com,
    required this.llantaPos8,
    required this.llantaPos8Com,
    required this.llantaPos9,
    required this.llantaPos9Com,
    required this.llantaPos10,
    required this.llantaPos10Com,
    required this.trasera3Img,
  });

  int folio;
  int carro;
  String usuario;
  DateTime fechaGuard;
  int anio;
  String motor;
  String placa;
  String marca;
  String noVin;
  String color;
  String modelo;
  double km;
  String nivelAceite;
  String combustible;
  bool motorOk;
  bool transmision;
  bool ejes;
  String sucursal;
  String firmaOp;
  String firmaRep;
  String frontalImg;
  bool placaDel;
  bool defensa;
  String defCom;
  bool cofreCentr;
  String cofreCentrCom;
  bool parrilla;
  String parrillaCom;
  bool faros;
  String farosCom;
  bool parabrisas;
  String parabrisasCom;
  bool copete;
  String copeteCom;
  bool engomados;
  bool conchasEspe;
  String conchasEspeCom;
  bool iave;
  String colchonImg;
  bool colch;
  String colchCom;
  String tableroImg;
  bool controles;
  String controlesCom;
  bool estereo;
  String estereoCom;
  String interiorImg;
  bool llavesEncend;
  String llavesEncendCom;
  bool tapiceria;
  String tapiceriaCom;
  bool limpiezaUnidad;
  String limpiezaUnidadCom;
  String video;
  bool carpeta;
  String carpetaCom;
  String accom;
  bool ac;
  String lateralDer1Img;
  bool defLateDer;
  String defLateDerCom;
  bool cofLateDer;
  String cofLateDerCom;
  bool espCofreDer;
  String espCofreDerCom;
  bool llantaPos2;
  String llantaPos2Com;
  String lateralDer2Img;
  bool faldonesDer;
  String faldonesDerCom;
  bool estribosDer;
  String estribosDerCom;
  bool puertaDer;
  String puertaDerCom;
  bool ventanasDer;
  String ventanasDerCom;
  bool conchEspeDer;
  String conchEspeDerCom;
  bool costadoDerCab;
  String costadoDerCabCom;
  bool aleronesDer;
  String aleronesDerCom;
  bool copeteCostDer;
  String copeteCostDerCom;
  String lateralIzq1Img;
  bool defLateIzq;
  String defLateIzqCom;
  bool cofLateIzq;
  String cofLateIzqCom;
  bool espCofreIzq;
  String espCofreIzqCom;
  bool llantaPos1;
  String llantaPos1Com;
  String lateralIzq2Img;
  bool faldonesIzq;
  String faldonesIzqCom;
  bool estribosIzq;
  String estribosIzqCom;
  bool puertaIzq;
  String puertaIzqCom;
  bool ventanasIzq;
  String ventanasIzqCom;
  bool conchEspIzq;
  String conchEspIzqCom;
  bool costadoIzqCab;
  String costadoIzqCabCom;
  bool aleronesIzq;
  String aleronesIzqCom;
  bool copeteCostIzq;
  String copeteCostIzqCom;
  String trampasImg;
  bool trampaIzq;
  String trampaIzqCom;
  bool trampaDer;
  String trampaDerCom;
  String acumuladoresImg;
  bool acum;
  String acumCom;
  String trampaDerImg;
  String trasera1Img;
  bool placaTrasera;
  bool portaloderas;
  String portaloderasCom;
  bool loderas;
  String loderasCom;
  bool bolsas;
  String bolsasCom;
  bool quinta;
  String quintaCom;
  bool lucesTras;
  String lucesTrasCom;
  bool espaldaCab;
  String eslpadaCabCom;
  bool mangueServicio;
  String mangueServicioCom;
  bool chirriones;
  String chirrionesCom;
  bool silenciador;
  String silenciadorCom;
  bool mallaEscape;
  String mallaEscapeCom;
  bool llantaPos3;
  String llantaPos3Com;
  String trasera2Img;
  bool guardafangos;
  String guardafangosCom;
  bool plataformaTrabajo;
  String plataformaTrabajoCom;
  bool miembrosTransv;
  String miembrosTransvCom;
  bool bastidores;
  String bastidoresCom;
  bool llantaPos4;
  String llantaPos4Com;
  bool llantaPos5;
  String llantaPos5Com;
  bool llantaPos6;
  String llantaPos6Com;
  bool llantaPos7;
  String llantaPos7Com;
  bool llantaPos8;
  String llantaPos8Com;
  bool llantaPos9;
  String llantaPos9Com;
  bool llantaPos10;
  String llantaPos10Com;
  String trasera3Img;

  factory Intercambio.fromJson(String str) =>
      Intercambio.fromMap(json.decode(str));

  String toJson() => json.encode(toMap());

  factory Intercambio.fromMap(Map<String, dynamic> json) => Intercambio(
        folio: json["folio"],
        carro: json["carro"],
        usuario: json["usuario"],
        fechaGuard: DateTime.parse(json["fechaGuard"]),
        anio: json["año"],
        motor: json["motor"],
        placa: json["placa"],
        marca: json["marca"],
        noVin: json["noVin"],
        color: json["color"],
        modelo: json["modelo"],
        km: double.parse(json["km"].toString()) , 
        nivelAceite: json["nivelAceite"],
        combustible: json["combustible"],
        motorOk: json["motorOk"],
        transmision: json["transmision"],
        ejes: json["ejes"],
        sucursal: json["sucursal"],
        firmaOp: json["firmaOp"],
        firmaRep: json["firmaRep"],
        frontalImg: json["frontalImg"],
        placaDel: json["placaDel"],
        defensa: json["defensa"],
        defCom: json["defCom"],
        cofreCentr: json["cofreCentr"],
        cofreCentrCom: json["cofreCentrCom"],
        parrilla: json["parrilla"],
        parrillaCom: json["parrillaCom"],
        faros: json["faros"],
        farosCom: json["farosCom"],
        parabrisas: json["parabrisas"],
        parabrisasCom: json["parabrisasCom"],
        copete: json["copete"],
        copeteCom: json["copeteCom"],
        engomados: json["engomados"],
        conchasEspe: json["conchasEspe"],
        conchasEspeCom: json["conchasEspeCom"],
        iave: json["iave"],
        colchonImg: json["colchonImg"],
        colch: json["colch"],
        colchCom: json["colchCom"],
        tableroImg: json["tableroImg"],
        controles: json["controles"],
        controlesCom: json["controlesCom"],
        estereo: json["estereo"],
        estereoCom: json["estereoCom"],
        interiorImg: json["interiorImg"],
        llavesEncend: json["llavesEncend"],
        llavesEncendCom: json["llavesEncendCom"],
        tapiceria: json["tapiceria"],
        tapiceriaCom: json["tapiceriaCom"],
        limpiezaUnidad: json["limpiezaUnidad"],
        limpiezaUnidadCom: json["limpiezaUnidadCom"],
        video: json["video"],
        carpeta: json["carpeta"],
        carpetaCom: json["carpetaCom"],
        accom: json["accom"],
        ac: json["ac"],
        lateralDer1Img: json["lateralDer1Img"],
        defLateDer: json["defLateDer"],
        defLateDerCom: json["defLateDerCom"],
        cofLateDer: json["cofLateDer"],
        cofLateDerCom: json["cofLateDerCom"],
        espCofreDer: json["espCofreDer"],
        espCofreDerCom: json["espCofreDerCom"],
        llantaPos2: json["llantaPos2"],
        llantaPos2Com: json["llantaPos2com"],
        lateralDer2Img: json["lateralDer2Img"],
        faldonesDer: json["faldonesDer"],
        faldonesDerCom: json["faldonesDerCom"],
        estribosDer: json["estribosDer"],
        estribosDerCom: json["estribosDerCom"],
        puertaDer: json["puertaDer"],
        puertaDerCom: json["puertaDerCom"],
        ventanasDer: json["ventanasDer"],
        ventanasDerCom: json["ventanasDerCom"],
        conchEspeDer: json["conchEspeDer"],
        conchEspeDerCom: json["conchEspeDerCom"],
        costadoDerCab: json["costadoDerCab"],
        costadoDerCabCom: json["costadoDerCabCom"],
        aleronesDer: json["aleronesDer"],
        aleronesDerCom: json["aleronesDerCom"],
        copeteCostDer: json["copeteCostDer"],
        copeteCostDerCom: json["copeteCostDerCom"],
        lateralIzq1Img: json["lateralIzq1Img"],
        defLateIzq: json["defLateIzq"],
        defLateIzqCom: json["defLateIzqCom"],
        cofLateIzq: json["cofLateIzq"],
        cofLateIzqCom: json["cofLateIzqCom"],
        espCofreIzq: json["espCofreIzq"],
        espCofreIzqCom: json["espCofreIzqCom"],
        llantaPos1: json["llantaPos1"],
        llantaPos1Com: json["llantaPos1com"],
        lateralIzq2Img: json["lateralIzq2Img"],
        faldonesIzq: json["faldonesIzq"],
        faldonesIzqCom: json["faldonesIzqCom"],
        estribosIzq: json["estribosIzq"],
        estribosIzqCom: json["estribosIzqCom"],
        puertaIzq: json["puertaIzq"],
        puertaIzqCom: json["puertaIzqCom"],
        ventanasIzq: json["ventanasIzq"],
        ventanasIzqCom: json["ventanasIzqCom"],
        conchEspIzq: json["conchEspIzq"],
        conchEspIzqCom: json["conchEspIzqCom"],
        costadoIzqCab: json["costadoIzqCab"],
        costadoIzqCabCom: json["costadoIzqCabCom"],
        aleronesIzq: json["aleronesIzq"],
        aleronesIzqCom: json["aleronesIzqCom"],
        copeteCostIzq: json["copeteCostIzq"],
        copeteCostIzqCom: json["copeteCostIzqCom"],
        trampasImg: json["trampasImg"],
        trampaIzq: json["trampaIzq"],
        trampaIzqCom: json["trampaIzqCom"],
        trampaDer: json["trampaDer"],
        trampaDerCom: json["trampaDerCom"],
        acumuladoresImg: json["acumuladoresImg"],
        acum: json["acum"],
        acumCom: json["acumCom"],
        trampaDerImg: json["trampaDerImg"],
        trasera1Img: json["trasera1Img"],
        placaTrasera: json["placaTrasera"],
        portaloderas: json["portaloderas"],
        portaloderasCom: json["portaloderasCom"],
        loderas: json["loderas"],
        loderasCom: json["loderasCom"],
        bolsas: json["bolsas"],
        bolsasCom: json["bolsasCom"],
        quinta: json["quinta"],
        quintaCom: json["quintaCom"],
        lucesTras: json["lucesTras"],
        lucesTrasCom: json["lucesTrasCom"],
        espaldaCab: json["espaldaCab"],
        eslpadaCabCom: json["eslpadaCabCom"],
        mangueServicio: json["mangueServicio"],
        mangueServicioCom: json["mangueServicioCom"],
        chirriones: json["chirriones"],
        chirrionesCom: json["chirrionesCom"],
        silenciador: json["silenciador"],
        silenciadorCom: json["silenciadorCom"],
        mallaEscape: json["mallaEscape"],
        mallaEscapeCom: json["mallaEscapeCom"],
        llantaPos3: json["llantaPos3"],
        llantaPos3Com: json["llantaPos3com"],
        trasera2Img: json["trasera2Img"],
        guardafangos: json["guardafangos"],
        guardafangosCom: json["guardafangosCom"],
        plataformaTrabajo: json["plataformaTrabajo"],
        plataformaTrabajoCom: json["plataformaTrabajoCom"],
        miembrosTransv: json["miembrosTransv"],
        miembrosTransvCom: json["miembrosTransvCom"],
        bastidores: json["bastidores"],
        bastidoresCom: json["bastidoresCom"],
        llantaPos4: json["llantaPos4"],
        llantaPos4Com: json["llantaPos4com"],
        llantaPos5: json["llantaPos5"],
        llantaPos5Com: json["llantaPos5com"],
        llantaPos6: json["llantaPos6"],
        llantaPos6Com: json["llantaPos6com"],
        llantaPos7: json["llantaPos7"],
        llantaPos7Com: json["llantaPos7com"],
        llantaPos8: json["llantaPos8"],
        llantaPos8Com: json["llantaPos8com"],
        llantaPos9: json["llantaPos9"],
        llantaPos9Com: json["llantaPos9com"],
        llantaPos10: json["llantaPos10"],
        llantaPos10Com: json["llantaPos10com"],
        trasera3Img: json["trasera3Img"],
      );

  Map<String, dynamic> toMap() => {
        "folio": folio,
        "carro": carro,
        "usuario": usuario,
        "fechaGuard": fechaGuard.toIso8601String(),
        "año": anio,
        "motor": motor,
        "placa": placa,
        "marca": marca,
        "noVin": noVin,
        "color": color,
        "modelo": modelo,
        "km": km,
        "nivelAceite": nivelAceite,
        "combustible": combustible,
        "motorOk": motorOk,
        "transmision": transmision,
        "ejes": ejes,
        "sucursal": sucursal,
        "firmaOp": firmaOp,
        "firmaRep": firmaRep,
        "frontalImg": frontalImg,
        "placaDel": placaDel,
        "defensa": defensa,
        "defCom": defCom,
        "cofreCentr": cofreCentr,
        "cofreCentrCom": cofreCentrCom,
        "parrilla": parrilla,
        "parrillaCom": parrillaCom,
        "faros": faros,
        "farosCom": farosCom,
        "parabrisas": parabrisas,
        "parabrisasCom": parabrisasCom,
        "copete": copete,
        "copeteCom": copeteCom,
        "engomados": engomados,
        "conchasEspe": conchasEspe,
        "conchasEspeCom": conchasEspeCom,
        "iave": iave,
        "colchonImg": colchonImg,
        "colch": colch,
        "colchCom": colchCom,
        "tableroImg": tableroImg,
        "controles": controles,
        "controlesCom": controlesCom,
        "estereo": estereo,
        "estereoCom": estereoCom,
        "interiorImg": interiorImg,
        "llavesEncend": llavesEncend,
        "llavesEncendCom": llavesEncendCom,
        "tapiceria": tapiceria,
        "tapiceriaCom": tapiceriaCom,
        "limpiezaUnidad": limpiezaUnidad,
        "limpiezaUnidadCom": limpiezaUnidadCom,
        "video": video,
        "carpeta": carpeta,
        "carpetaCom": carpetaCom,
        "accom": accom,
        "ac": ac,
        "lateralDer1Img": lateralDer1Img,
        "defLateDer": defLateDer,
        "defLateDerCom": defLateDerCom,
        "cofLateDer": cofLateDer,
        "cofLateDerCom": cofLateDerCom,
        "espCofreDer": espCofreDer,
        "espCofreDerCom": espCofreDerCom,
        "llantaPos2": llantaPos2,
        "llantaPos2com": llantaPos2Com,
        "lateralDer2Img": lateralDer2Img,
        "faldonesDer": faldonesDer,
        "faldonesDerCom": faldonesDerCom,
        "estribosDer": estribosDer,
        "estribosDerCom": estribosDerCom,
        "puertaDer": puertaDer,
        "puertaDerCom": puertaDerCom,
        "ventanasDer": ventanasDer,
        "ventanasDerCom": ventanasDerCom,
        "conchEspeDer": conchEspeDer,
        "conchEspeDerCom": conchEspeDerCom,
        "costadoDerCab": costadoDerCab,
        "costadoDerCabCom": costadoDerCabCom,
        "aleronesDer": aleronesDer,
        "aleronesDerCom": aleronesDerCom,
        "copeteCostDer": copeteCostDer,
        "copeteCostDerCom": copeteCostDerCom,
        "lateralIzq1Img": lateralIzq1Img,
        "defLateIzq": defLateIzq,
        "defLateIzqCom": defLateIzqCom,
        "cofLateIzq": cofLateIzq,
        "cofLateIzqCom": cofLateIzqCom,
        "espCofreIzq": espCofreIzq,
        "espCofreIzqCom": espCofreIzqCom,
        "llantaPos1": llantaPos1,
        "llantaPos1com": llantaPos1Com,
        "lateralIzq2Img": lateralIzq2Img,
        "faldonesIzq": faldonesIzq,
        "faldonesIzqCom": faldonesIzqCom,
        "estribosIzq": estribosIzq,
        "estribosIzqCom": estribosIzqCom,
        "puertaIzq": puertaIzq,
        "puertaIzqCom": puertaIzqCom,
        "ventanasIzq": ventanasIzq,
        "ventanasIzqCom": ventanasIzqCom,
        "conchEspIzq": conchEspIzq,
        "conchEspIzqCom": conchEspIzqCom,
        "costadoIzqCab": costadoIzqCab,
        "costadoIzqCabCom": costadoIzqCabCom,
        "aleronesIzq": aleronesIzq,
        "aleronesIzqCom": aleronesIzqCom,
        "copeteCostIzq": copeteCostIzq,
        "copeteCostIzqCom": copeteCostIzqCom,
        "trampasImg": trampasImg,
        "trampaIzq": trampaIzq,
        "trampaIzqCom": trampaIzqCom,
        "trampaDer": trampaDer,
        "trampaDerCom": trampaDerCom,
        "acumuladoresImg": acumuladoresImg,
        "acum": acum,
        "acumCom": acumCom,
        "trampaDerImg": trampaDerImg,
        "trasera1Img": trasera1Img,
        "placaTrasera": placaTrasera,
        "portaloderas": portaloderas,
        "portaloderasCom": portaloderasCom,
        "loderas": loderas,
        "loderasCom": loderasCom,
        "bolsas": bolsas,
        "bolsasCom": bolsasCom,
        "quinta": quinta,
        "quintaCom": quintaCom,
        "lucesTras": lucesTras,
        "lucesTrasCom": lucesTrasCom,
        "espaldaCab": espaldaCab,
        "eslpadaCabCom": eslpadaCabCom,
        "mangueServicio": mangueServicio,
        "mangueServicioCom": mangueServicioCom,
        "chirriones": chirriones,
        "chirrionesCom": chirrionesCom,
        "silenciador": silenciador,
        "silenciadorCom": silenciadorCom,
        "mallaEscape": mallaEscape,
        "mallaEscapeCom": mallaEscapeCom,
        "llantaPos3": llantaPos3,
        "llantaPos3com": llantaPos3Com,
        "trasera2Img": trasera2Img,
        "guardafangos": guardafangos,
        "guardafangosCom": guardafangosCom,
        "plataformaTrabajo": plataformaTrabajo,
        "plataformaTrabajoCom": plataformaTrabajoCom,
        "miembrosTransv": miembrosTransv,
        "miembrosTransvCom": miembrosTransvCom,
        "bastidores": bastidores,
        "bastidoresCom": bastidoresCom,
        "llantaPos4": llantaPos4,
        "llantaPos4com": llantaPos4Com,
        "llantaPos5": llantaPos5,
        "llantaPos5com": llantaPos5Com,
        "llantaPos6": llantaPos6,
        "llantaPos6com": llantaPos6Com,
        "llantaPos7": llantaPos7,
        "llantaPos7com": llantaPos7Com,
        "llantaPos8": llantaPos8,
        "llantaPos8com": llantaPos8Com,
        "llantaPos9": llantaPos9,
        "llantaPos9com": llantaPos9Com,
        "llantaPos10": llantaPos10,
        "llantaPos10com": llantaPos10Com,
        "trasera3Img": trasera3Img,
      };
}
